""" Constants """
MAX_DELIVERY_FEE = 1500
FREE_DELIVERY_CART_VALUE = 20000
NO_SURCHARGE_MIN_CART_VALUE = 1000
RUSH_HOUR_MULTIPLIER = 1.2
""" Distance constants """
STARTING_DISTANCE = 1000
DISTANCE_STARTING_FEE = 200
DISTANCE_HALF_KM_FEE = 100
""" Items constants """
MAX_ITEMS_NO_SURCHARGE = 4
ADDITIONAL_FEE_PER_ITEM = 50
MAX_ITEMS_NO_BULK_FEE = 12
ITEMS_BULK_FEE = 120
""" Order format constants """
MIN_CART_VALUE = 1
MIN_DELIVERY_DISTANCE = 0
MIN_NUMBER_OF_ITEMS = 1
